# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.CharField(default=b'Unspecified', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'Unspecified', max_length=50)),
                ('LTP', models.CharField(default=b'0-0-0', max_length=5)),
                ('credits', models.IntegerField(choices=[(0, b'0'), (3, b'3'), (4, b'4'), (5, b'5')], default=0)),
                ('courseType', models.BooleanField(choices=[(1, b'Credit'), (0, b'Audit')], default=True)),
                ('gradesUploaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[(b'U', b'U'), (b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'D', b'D'), (b'F', b'F')], default=b'U', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('role', models.IntegerField(choices=[(0, b'Student'), (1, b'Instructor'), (2, b'Admin')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GMS.User')),
                ('branch', models.BooleanField(choices=[(1, b'CSE'), (2, b'EE'), (3, b'ME')], default=1)),
                ('batch', models.BooleanField(choices=[(0, b'UG'), (1, b'PG')], default=0)),
                ('year', models.IntegerField(default=2015)),
                ('allCourses', models.ManyToManyField(to='GMS.Course')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GMS.Instructor'),
        ),
    ]
